name: integration_tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout Git branch
        uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy Cython coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Start Docker containers for Zookeeper and Kafka 
        run: docker-compose -f tests/kafka_environment/docker-compose.yml up -d
      - name: Test with pytest
        run: |
          coverage run --source apf -m pytest -x -s tests/integration/
          coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: integration
